### ISSUE TITLE
Octoremote only partially working

### ISSUE THREAD

**Issue by gcw843** [pkElectronics/OctoPrint-Octoremote#1]
I'm using a 4x4 mebrane keypad and the latest version of octoprint on RPI but can't get Octoremote to work properly.  The following keys are working: Change Jog Distance, Increment Z Axis, Home X&Y Axis, Home Z axis, Stop Print, Pause Print, Start Print.  The Increment Y Axis  and Increment X Axis keys work but they are swapped ie-X key moves Y axis and Y key moves X axis. If I swap their values in the arduino.ino for the key code matrix they work as they're supposed. Nothing works on Row 3 and none of the Decrement buttons work. Could this be due to negative signs in the payloads for them? I've checked all of the wiring connections, changed the pin assignments, and verified proper connections. The problem is exactly the same on 3 different arduinos

**Comment by pkElectronics** [comment]
Sorry for the late reply, I am not constantly checking whats going on with my github projects.

Have you checked if the keypad is working without the Octoremote Arduino code but with the default Arduino Keypad libary? Sometimes when you salvage Keypads from old electronics the connections are somehow messed up.

**Comment by gcw843** [comment]
Hey – thanks for replying! I’ve tried it with 5 different keypads. All of them are the membrane 4x4 ones from ebay. I’ve ordered a standard hardware keypad like on a phone.  Yes – I’ve tried all of the libraries but no joy. Octoremote is a great idea & I’d really like to get it working.

 

Thanks!

 

Gene

**Comment by pkElectronics** [comment]
So do the keypads work with a different library? Can you see if the TX led
is flashing on every push of a button?

gcw843 <notifications@github.com> schrieb am So., 13. Aug. 2017, 19:13:

**Comment by gcw843** [comment]
Yes all keys work with keyboard library – on all keypads

**Comment by pkElectronics** [comment]
Ok
can you check if the Arduino transmits all keypresses to the Plugin? I try to find out if it´s an issue with the arduino or with the Octoprint plugin.

**Comment by gcw843** [comment]
Will do. Have a print running now

**Comment by pkElectronics** [comment]
Hey there,

any news on the issue?
