### ISSUE TITLE
Octoremote crashes instantly on Android

### ISSUE THREAD

**Issue by Budge72** [pkElectronics/OctoPrint-Octoremote#10]
This is my first github post, so my apologies for not knowing the format.  Octoremote keeps crashing as soon as I open the app on my Galaxy S8+.  I'm running Android 8.0.0.  I tried uninstall/reinstalling, but not joy.

Crash report log
Report type
Crash

Package Name
com.kabacon.octoremote

Package version
12

Package version name
1.2

**Comment by pkElectronics** [comment]
I don´t really get  what this project has to do with android
