### ISSUE TITLE
Possible to use USB keyboard instead of Arduino/Keypad?

### ISSUE THREAD

**Issue by rmoorewrs** [pkElectronics/OctoPrint-Octoremote#2]
How hard would it be for your plugin to take input from a standard HID/USB keyboard (plugged into the Raspberry Pi) instead of from the custom-made keypad/Arduino? That would be really convenient. 

While it's nice to have a custom dedicated keypad (and not terribly difficult), it's yet another project and sometimes it would be nice to just plug in a regular old wired (or usb-dongle wireless) keyboard and go.

Come to think of it, I'd probably use one of [these USB Number Pads.]( https://www.amazon.com/Numeric-Jelly-Comb-Portable-Computer/dp/B01E8TTWZ2/).

Is all of the serial-handling code in `octoprint_OctoRemote/__init__.py`?

**Comment by rmoorewrs** [comment]
BTW, I forked your repo to do the USB keyboard thing myself. I'm new to forking from someone else's work. I've tried to give proper credit, and my intention is to do so, but might've gotten something wrong. If so, please let me know and I'll correct it. Thanks.

**Comment by pkElectronics** [comment]
Well, sorry for my late reply. I am not constantly checking what happens to my github projects. Unfortunatly i am not enough into python and plugin development to answer your question. If you like, you could add the features you want, make it configurable in the settings page and make a pull request so I will merge it back into the original repo and it will be available through the official Octoprint Plugin System.

**Comment by rmoorewrs** [comment]
Sounds good, I started on it, but have other pressing issues.. it would be
a nice feature and I don't think that difficult to implement (your custom
keyboard was probably much more challenging)

**Comment by ericrisch** [comment]
any news on this feature?

**Comment by token47** [comment]
Yeah, I would love it too. Waiting for it to come.

**Comment by pkElectronics** [comment]
It´s definitly possible to implement this but requires, But at the moment I lack motivation to do so.

**Comment by pkElectronics** [comment]
It's definitely possible to implement this but at the moment I lack motivation to do so. Sorry guys but feel free to do it yourself and make a pull request.

**Comment by token47** [comment]
I implemented this. It's not a plugin, though, but works very well.

https://github.com/token47/octoprint-usb-keypad

**Comment by token47** [comment]
I implemented this. It's not a plugin, though, but works very well.

https://github.com/token47/octoprint-usb-keypad

@rmoorewrs @ericrisch
