### ISSUE TITLE
Rotary encoder / custom buttons

### ISSUE THREAD

**Issue by Stargrove1** [pkElectronics/OctoPrint-Octoremote#3]
Hello, would it be possible to extend the code to accept an encoder input (https://de.aliexpress.com/item/CNC-electronic-hand-wheel-diameter-60mm-input-DC-5v-6-pin-hand-wheel-siliver-color/32729042250.html?spm=a2g0x.10010108.1000014.9.ef920QlVq6g&traffic_analysisId=recommend_3035_null_null_null&scm=1007.13338.80878.000000000000000&pvid=6a56f7f6-2e96-412e-831c-b281ca4b4b23&tpp=1) to set an axis and control distance and speed by the wheel?

**Comment by pkElectronics** [comment]
Hey there. Sorry for the late reply, I do not check my github account very regulary. I believe adding a rotary encoder would not be that hard as the controller is based on the Arduino Leonardo. I am currently working on a new hardware revision and will add some headers for attaching the encoder. 

I will keep you informed on any progress

**Comment by Stargrove1** [comment]
That would be awesome, I just ordered one few days ago, right now positioning with 1, 10, 100mm is not as comfortable as I expect it to be.
