### ISSUE TITLE
Can't seem to connect

### ISSUE THREAD

**Issue by TTVert** [pkElectronics/OctoPrint-Octoremote#4]
I'm using this Plugin, using v1.2 of the android app and octoprint on a pi.   I can access the url I specified via  web browser as well as this phone which has the octoremote apk installed however no love from the android app, just never connects (Get an instant "could not retrieve files".  I even connected to wifi on same LAN as the pi and specified the local hostname as well as just the IP..  I've ensured the API was correct as well.  Is there anything else I can check?  Any logs generated by the app?   Oh and yeah I do have the Plugin enabled.

Thanks much, hope to get this working as it seems much more elegant than going to the internet facing URL.

Dave

**Comment by pkElectronics** [comment]
Hi Dave,

I don´t really get how my plugin affects the connection between octoprint and your app. Are you sure you opened the issue on the right plugin?

Regards 
Pascal
