### ISSUE TITLE
Send data to Arduino

### ISSUE THREAD

**Issue by mullinsen** [pkElectronics/OctoPrint-Octoremote#5]
Hi!
I am part in a group of students writing a Bachelor's thesis. The objective is to construct an automatic feeder for 3D-printers. However, we are unfortunately barely used to coding. 
In this matter, I am wondering if the Octoremote is able to send data to Arduino IDE through Serial.read, i.e. when print is done? So far I can not seem to recieve any data in the serial monitor with a virtual printer. Is this possible, or should we attempt something else?

**Comment by pkElectronics** [comment]
Hi, 

please excuse my late reply, I´m not checking the issues page on a regular basis. You can in fact use the onboard serial port of the Octoremote (like rx and tx pins on a regular arduino) to interface with additional hardware.  But it will require another USB to Serial converter. It is not possible to hook up the Arduino IDE to the USB VCP used for communication between the OctoRemote and the OctoPrint instance as this is already blocked for communication between said parts.
