### ISSUE TITLE
bad crc issue

### ISSUE THREAD

**Issue by zverugaz** [pkElectronics/OctoPrint-Octoremote#6]
Hi. I think I found bug in plugin - on my system (Arduino IDE 1.8.5) it not work properly. When I start debugging I found that crc sum from arduino board not like crc on plugin side. I fix it when change in arduino scatch all crc.update call from
`crc.update(something);`
to
`crc.update(byte(something));`

**Comment by pkElectronics** [comment]
Do you have the exact line you changed and also the version of the crc library?

**Comment by zverugaz** [comment]
Its in arduino/OctoRemoteV1/OctoRemoteV1.ino
all crc.update call crc.update(something);
like on lines 100, 101, 102, 103 etc.
My CRC32 version is 2.0.0

**Comment by pkElectronics** [comment]
Should be fixed in V3
